# set vimfiles folder, default -> vimfiles
vimfiles_folder: vimfiles

# set vim config file, default -> .vimrc
vim_config: .vimrc

# set vim folder, default -> .vim
vim_folder: .vim

# set git sources
git_bundles:
  #git://github.com/Townk/vim-autoclose.git
  #git://github.com/altercation/vim-colors-solarized.git
  #git://github.com/astashov/vim-ruby-debugger.git
  #git://github.com/ervandew/supertab.git
  #git://github.com/godlygeek/tabular.git
  #git://github.com/msanders/snipmate.vim.git
  #git://github.com/scrooloose/nerdtree.git
  #git://github.com/terryma/vim-multiple-cursors.git
  #git://github.com/tomtom/tcomment_vim.git
  #git://github.com/tpope/vim-bundler.git
  #git://github.com/tpope/vim-commentary.git
  #git://github.com/tpope/vim-haml.git
  #git://github.com/tpope/vim-pathogen.git
  #git://github.com/tpope/vim-rails.git
  #git://github.com/tpope/vim-repeat.git
  #git://github.com/tpope/vim-rvm.git
  #git://github.com/tpope/vim-surround.git
  #git://github.com/vim-ruby/vim-ruby.git
  #git://github.com/vim-scripts/FuzzyFinder.git
  #git://github.com/vim-scripts/L9.git
  # git://github.com/tsaleh/vim-matchit.git
  #  git://github.com/benmills/vimux.git
  #  git://github.com/pangloss/vim-javascript.git
  #  git://github.com/scrooloose/snipmate-snippets.git
  #  git://github.com/timcharper/textile.vim.git
  #  git://github.com/tpope/vim-abolish.git
  #  git://github.com/tpope/vim-eunuch.git
  #  git://github.com/tpope/vim-fugitive.git
  #  git://github.com/tpope/vim-git.git
  #  git://github.com/tpope/vim-markdown.git
  #  git://github.com/tpope/vim-ragtag.git
  #  git://github.com/tpope/vim-sleuth.git
  #  git://github.com/tpope/vim-tbone.git
  #  git://github.com/tsaleh/vim-shoulda.git
  #  git://github.com/tsaleh/vim-tmux.git
  #  git://github.com/vim-scripts/mru.vim.git
  # set vim.org sources
  # format -> name, download_id, type
vim_org_bundles: |
  IndexedSearch, 7062, plugin
  jquery, 15752, syntax
