#!/usr/bin/env ruby

require 'fileutils'
require 'open-uri'
require "git"

git_bundles = [
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/ervandew/supertab.git",
  "git://github.com/godlygeek/tabular.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tomtom/tcomment_vim.git",
  "git://github.com/Townk/vim-autoclose.git",
  "git://github.com/tpope/vim-abolish.git",
  "git://github.com/tpope/vim-bundler.git",
  "git://github.com/tpope/vim-commentary.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-pathogen.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-rvm.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tsaleh/vim-matchit.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tsaleh/vim-tmux.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/vim-scripts/FuzzyFinder.git",
  "git://github.com/vim-scripts/L9.git",
  "git://github.com/vim-scripts/mru.vim.git",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

# git clone
def clone_git(url,dir)
    FileUtils.rm_rf(dir) if File.directory?(dir)
    puts "unpacking #{url} into #{dir}"
    Git.clone(url,dir)
end

# go to bundle dir 
bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.mkdir (bundles_dir) unless File.directory?(bundles_dir)
FileUtils.cd(bundles_dir)


# load with git
git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  begin
    if Git.open(dir)
      g = Git.open(dir)
      puts "updating #{dir}"
        g.with_working(dir) do
        g.pull
      end
    else
      clone_git(url,dir)
    end
  rescue
    clone_git(url,dir)
  end
end

# load from vim.org
vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

